### ISSUE TITLE
[bug] unable to use chocopedia on chocobo when on remote server

### ISSUE THREAD

**Issue by danpolanco** [clienthax/ChocoCraft2#13]
It looks like in EntityChocobo.java, CC2 check if the client is remote and if they are, they aren't allowed to open the Chocopedia gui. Yeah?

```
if (!worldObj.isRemote) {
    if (player.getHeldItem() != null && player.getHeldItem().getItem() == Additions.chocopediaItem && isTamed() && getOwner() == player) {
        ChocoCraft2.proxy.openChocopedia(this);
        return true;
    }
}
```

So the gui opens in single player, but not multiplayer.

**Comment by clienthax** [comment]
Mhm nice catch, i need to change it to use a packet anywho,

**Comment by hsyyid** [comment]
Was fixed by @clienthax a while back
