### ISSUE TITLE
[enhancement] straw - and maybe other items - must be in specific craft bins to work

### ISSUE THREAD

**Issue by danpolanco** [clienthax/ChocoCraft2#14]
Probably something on your todo list already but making an issue just incase. Pictures explain it best:

**Works in top section of crafting table**
![screen shot 2015-12-23 at 11 14 34 pm](https://cloud.githubusercontent.com/assets/3826143/11990448/035d7492-a9cb-11e5-9dd6-1a2cf5b4e248.png)

**Doesn't work below**
![screen shot 2015-12-23 at 11 14 54 pm](https://cloud.githubusercontent.com/assets/3826143/11990449/057ae58e-a9cb-11e5-98b2-47e1cc089eae.png)

**Comment by hsyyid** [comment]
I'll fix this one.
