### ISSUE TITLE
[MC1.8.0] Multiplayer Crash

### ISSUE THREAD

**Issue by BlackYamato** [clienthax/ChocoCraft2#8]
Environment:
・Java 8u66 64bit
・Minecraft 1.8.0
・Minecraft Forge 11.14.4.1563
・ChocoCraft2 Alpha 2 - 0.0.2

Client Crash Report:
http://pastebin.com/UPHcKt49

**Comment by hsyyid** [comment]
Try updating Forge.

**Comment by BlackYamato** [comment]
Minecraft Forge 11.14.4.1577
It was a similar result in this version.

This error seems to occur when someone got on the chocobo.
Person of the client that riding a chocobo will not crash.
Client of people who are in the vicinity of this person will crash.

**Comment by hsyyid** [comment]
Fixing it

**Comment by BlackYamato** [comment]
Thanks so much.

**Comment by danpolanco** [comment]
More maybe relevant information:

If you are far enough away that the chocobo doesn't render but the person mounts, the crash doesn't happen. However, the person appears to just stand in the same spot until they unmount.

**Comment by danpolanco** [comment]
Is this as simple as changing `EntityPlayerSP riderSP = (EntityPlayerSP) rider;` to `EntityClientPlayerMP riderMP = (EntityClientPlayerMP) rider;` in ClientProxy.java?

**Comment by danpolanco** [comment]
Nvm. Gonna keep working on it.
